language: php
branches:
  only: master
php:
  - 5.5.9
  # - 5.6
  # - 7.0
  # - hhvm
  # - nightly
env:
  - SYMFONY_VERSION=^3.0
cache:
  directories:
    - $HOME/.composer/cache/files
before_script:
  - composer self-update
  - composer require symfony/symfony:${SYMFONY_VERSION}
script:
  - mkdir -p build/logs
  - phpunit
after_script:
  - php vendor/bin/coveralls -v
